### ISSUE TITLE
Automated testing error

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/gravity-force-lab-basics#8] opened 2017-03-16 06:32 UTC
```
gravity-force-lab-basics : fuzz : require.js : run
Uncaught Error: Assertion failed: must have non zero distance between objects
Error: Assertion failed: must have non zero distance between objects
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/assert/js/assert.js:21:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/inverse-square-law-common/js/model/InverseSquareLawModel.js?bust=1489645540364:61:20
    at Array.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/axon/js/DerivedProperty.js?bust=1489645540364:76:57)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/axon/js/Emitter.js?bust=1489645540364:147:49)
    at Property._notifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/axon/js/Property.js?bust=1489645540364:208:29)
    at Property._setAndNotifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/axon/js/Property.js?bust=1489645540364:197:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/axon/js/Property.js?bust=1489645540364:141:16)
    at drag (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/gravity-force-lab/js/gravity-force-lab/view/MassNode.js?bust=1489645540364:280:36)
    at Object.move (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/scenery/js/input/SimpleDragHandler.js?bust=1489645540364:130:29)
    at Input.dispatchToPointer (https://bayes.colorado.edu/continuous-testing/snapshot-1489641307817/scenery/js/input/Input.js?bust=1489645540364:773:27)
Approximately 3/15/2017, 11:15:07 PM
```

**Comment by jessegreenberg** [comment] 2017-05-02 23:31
Unable to reproduce locally, and I don't see this on continuous testing. Closing.

**Closed by jessegreenberg** 2017-05-02 23:31 UTC
Labels: type:automated-testing, type:bug
