### ISSUE TITLE
(Voicing) Distance issue - only moved sphere updates its distance value

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#283] opened 2021-07-02 19:43 UTC
I'm reviewing the version to be used in the next survey.

Both spheres' distance value needs to update when one sphere is moved, so that the next interaction with the other sphere provides the correct distance value on focus, click, tap, etc.

**Comment by terracoda** [comment] 2021-07-02 20:11
This is an issue for all inputs.

**Comment by jessegreenberg** [comment] 2021-07-02 21:21
Should be fixed in the above commit.

**Comment by jessegreenberg** [comment] 2021-07-02 22:35
This should be fixed in this version, @terracoda can you please review? https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.32/phet/gravity-force-lab-basics_en_phet.html?voicingSurvey=true

**Comment by terracoda** [comment] 2021-07-03 14:59
This is good, except when you switch between distance checked and not checked. You need to move the spheres before you hear the new mode. 

Can you fix that, too. The distance is updating. You just need to update the description mode (kilometers or qualitative distance) when the checkbox gets checked.

**Comment by terracoda** [comment] 2021-07-03 15:00
If you can't fix this before survey time, it's not a show stopper. The information is not incorrect, it just isn't in the right mode.

**Comment by jessegreenberg** [comment] 2021-07-05 17:53
This has been resolved, and I checked with @terracoda over slack who confirmed that the problem was fixed. Closing this issue.

**Closed by jessegreenberg** 2021-07-05 17:53 UTC
Labels: priority:2-high, type:bug
