### ISSUE TITLE
Sim crashes on Active wrapper

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#198] opened 2020-03-09 21:45 UTC
For ES6 Testing
In the Active wrapper, when you de-activate and try to reactivate the sim, it crashes and freezes. Console error bellow.
![reactivate](https://user-images.githubusercontent.com/41024075/76260197-e93e4500-621c-11ea-87f9-b38b236f3768.png)

**Comment by zepumph** [comment] 2020-03-16 19:26
This is a duplicate of #197, see the second error in the console. Closing

**Closed by zepumph** 2020-03-16 19:26 UTC
Labels: type:bug
