### ISSUE TITLE
(Self-Voicing) Reading highlight a little too sticky

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#209] opened 2020-07-20 15:07 UTC
After reading a block and then interacting, the reading highlight does not disappear and is not responsive tot eh new interaction.

It should likely disappear once something else is interacted with.

![Screen Shot 2020-07-20 at 12 32 25 PM](https://user-images.githubusercontent.com/1902116/87953123-382a9f80-ca85-11ea-8ead-24cea44bd2dd.png)

![Screen Shot 2020-07-20 at 12 36 27 PM](https://user-images.githubusercontent.com/1902116/87953481-aa02e900-ca85-11ea-845e-423501a1ad59.png)

**Comment by jessegreenberg** [comment] 2020-07-22 17:50
Are you able to get this to happen consistently @terracoda? In general, the highlight disppears for me the moment I try to read something else.

**Comment by jessegreenberg** [comment] 2020-07-22 17:54
It is possible that changes for #210 have fixed this.

**Comment by jessegreenberg** [comment] 2020-07-22 18:15
I think this is further improved by the above commit. @terracoda can you please test to make sure?

**Comment by terracoda** [comment] 2020-07-23 14:41
Much better, thanks!

**Comment by jessegreenberg** [comment] 2020-07-24 17:08
Hmm, this is still happening in a much more broken way now, a recent commit probably broke this.

**Comment by jessegreenberg** [comment] 2020-07-24 17:15
It looks like the issue is specific to Safari, the `end` event on the utterance does not fire and so the speaking highlight stays forever.

**Comment by terracoda** [comment] 2020-07-24 17:18
I will re-test.

**Comment by jessegreenberg** [comment] 2020-07-24 17:20
I think this may be a differnt issue, and was probably present in all versions thus far. THe cause is https://github.com/phetsims/gravity-force-lab-basics/issues/215.

**Comment by jessegreenberg** [comment] 2020-07-24 17:22
Re-closing this issue, moving to #215.

**Closed by jessegreenberg** 2020-07-24 17:22 UTC
Labels: status:ready-for-review

**Comment by terracoda** [comment] 2020-07-24 17:47
I said on slack:

> For me, it seems to work better than it did before. As long as I click on something else the highlight goes away.
>But if I use the keyboard, the reading highlight stays.
> Maybe you can do something like, if focus moves, stop highlighting.
> I'll comment in the issue.

But the issue is indeed because of #215
