### ISSUE TITLE
Studio sliders should support dynamic range

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab-basics#44] opened 2018-01-24 05:08 UTC
See https://github.com/phetsims/phet-io-wrappers/issues/45.  We'll work on this when we do the stable PhET-iO redesign for the sim.

**Comment by zepumph** [comment] 2019-08-09 00:27
This is a duplicate of https://github.com/phetsims/gravity-force-lab/issues/172. Closing

**Closed by zepumph** 2019-08-09 00:27 UTC
Labels: dev:phet-io, phet-io:studio, priority:5-deferred, status:on-hold
